initramfs-live-install: comment out allarch inherit to resolve no provider
initramfs-live-install is only compatible with i.86|x86_64 so
shouldn't inherit 'allarch'.  This comments it out.

More specifically, commit 52295fa3deef3b0374b99829626d524cefae6001
(Improve handling of 'all' architecture recipes and their interaction
with sstate) sets TARGET_ARCH which due to the COMPATIBLE_HOST setting
in the recipe causes it to be skipped and gives the following error
for any -live build:

NOTE: Resolving any missing task queue dependencies
NOTE: Runtime target 'initramfs-live-install' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['initramfs-live-install']
ERROR: Required build target 'core-image-sato-live' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-sato-live', 'core-ima\
ge-minimal-initramfs', 'initramfs-live-install']
ERROR: Nothing RPROVIDES 'initramfs-live-install'

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>

Commented out with explaination instead of remove

Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>